### PR TITLE
Uniform testing service

### PR DESCRIPTION
**Pull request by tapaswenipathak**
@mamtashukla can we merge this?

### CODE REVIEW

**Comment by tapaswenipathak** [comment]
@Aashi15bansal @mamtashukla What with this PR? Can we merge this?

**Comment by mamtashukla** [comment]
@tapaswenipathak  I checked the branch uniform-testing-service and found all PRs merged till date.
Closing this.

**Comment by mamtashukla** [comment]
@tapaswenipathak I am trying to fix merge issue and created this PR -https://github.com/alice-sieve/Linux-Kernel/pull/94. But still the issue persists.

**Comment by tapaswenipathak** [comment]
On Wed, Jul 17, 2019 at 1:08 PM Mamta <notifications@github.com> wrote:
>
> @tapaswenipathak I am fixing merge issue and created this PR -#94. But still the issue is present.

Don't waste time in fixing merge issue, directly commit. Left a note in Slack.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Tapasweni

**Comment by tapaswenipathak** [comment]
👋

**Comment by tapaswenipathak** [comment]
Merge?

**Pull request closed without merging**
