### PR TITLE
Kernel API

### PR DESCRIPTION
**Pull request by tapaswenipathak**
@mamtashukla can we merge this?

### CODE REVIEW

**Comment by tapaswenipathak** [comment]
@Aashi15bansal @mamtashukla What with this PR? Can we merge this?

**Comment by mamtashukla** [comment]
Yes, this can be merged. 
But README.md has some conflicts.

**Comment by tapaswenipathak** [comment]
np, delete readme, get this merged.

**Comment by tapaswenipathak** [comment]
👋

**Comment by mamtashukla** [comment]
Pinged on slack.

**Comment by tapaswenipathak** [comment]
Directly push on main branch.

**Pull request merged**
